opencurve/curveadm

README.md
Delete the '$' in front of each command line to facilitate copying it.
=> README: Delete the '$' in front of each command line to facilitate copying it

cli/command/check.go, cli/command/mount.go, cli/command/umount.go
We get different result when check /mnt/curve-fuse/ and /mnt/curve-fuse,
we want to get the same result of this command, fix this issue by triming
the / suffix of mountpoint during mount/umount/check.
Fixes: #19
=> Ignore / when mount/umount/check mountpoint

scripts/install.sh
partly fix issue #32
This change has been tested on Ubuntu 20.04 and CentOS 8, and without this change the shell syntax error occurs on Ubuntu 20.04, but not on CentOS8.
=> fix shell syntax error

cli/command/clean.go, cli/command/cluster/remove.go, cli/command/config/commit.go, cli/command/stop.go, cli/command/support.go, internal/tools/upgrade.go, internal/tui/common/tui.go
Closing #13 
```
$ curveadm cluster rm fs
Warning: This operation will remove cluster fs, and all data in it will be cleaned.
Do you want to continue? [YES/No]: (default=No) YES
Deleted cluster 'fs'
$ curveadm clean
Warning: clean role=* host=* id=* only=log,data,container now, log,data,container in it will be cleaned.
Do you want to continue? [YES/No]: (default=No) YES
Clean Service: [OK]
$ curveadm stop
Warning: Stop all service now, client IO will be hang!
Do you want to continue? [YES/No]: (default=No) YES
Stop Service: [OK]
```
=> add warning for damage operations

internal/configure/client/fs/client.go, internal/task/task/common/create_pool.go, internal/task/task/fs/mount.go
fix mountpoint same in container:
treat /curvefs/client/mnt as the prefix of the mount path Mount into the
container
=> curveadm/mount: fix path same

internal/task/step/shell.go
Closes: #55
When data dir is umounted, the check will failed on CentOS, because
we check suffix must be 'not mounted', but on CentOS it is 'not mounted.',
then the format will be failed.
=> curvebs: fix mount status check fail during format chunkserver

configs/bs/cluster/format.yaml, configs/bs/stand-alone/format.yaml, internal/configure/format/format.go
Close #60 
```
support disk range like: /dev/sd[b-e]:/data/chunkserver[1-4]:90
if you want to exclude disk /dev/sdc and sdd, use this:
/dev/sd[b-e,^cd]:/data/chunkserver[1-2]:80
if you have too many disks on a host(more than 26), use these:
/dev/sd[a-z]:/data/chunkserver[1-26]:70
/dev/sda[a-z]:/data/chunkserver[27-52]:60
also support disk and mountpoint with suffix, like:
/dev/nvme[0-9]n1:/data/chunkserver[0-9]n1:90
```
=> feature(curvebs): support flexible format.yaml

cli/command/target/add.go
if volume name doesn't start with '/', give prompt message to user.
=> curvebs: add volume format check for target add command

cli/curveadm.go
```
[curve@localhost curveadm]$ cat ~/.curveadm/logs/curveadm-audit-2022-03-22.log
[2022/03/22 09:48:16.486 +08:00] [INFO] [curveadm.go:59] [status] [result=success]
[curve@localhost curveadm]$ cat ~/.curveadm/logs/curveadm-audit-2022-03-24.log
[2022/03/24 09:37:35.073 +08:00] [INFO] [curveadm.go:59] [status] [Cluster=mybs] [result=success]
```
=> add cluster name to audit log

internal/task/scripts/wait.go
bugfix: fixed execute curl without timout in wait script, close #89
=> bugfix: set timeout of curl instruction when executing wait.sh

cli/command/cluster/list.go, cli/command/status.go, internal/task/task/common/get_status.go, internal/task/tasks/items.go, internal/tui/clusters.go, internal/tui/service/status.go
OSPP Project Number: 222990287
Problem Summary:
Display port number that each service is listening to by default when user uses `curveadm status` command.
**internal/tui/service: status.go**
**internal/task/task/common: get_status.go**
- added additional step in `NewGetServiceStatusTask` function. New step executes pipeline command inside container to extract port numbers the service is listening to.
- If pipleline command returns any message other than port number(e.g. error message), empty string will be returned as result.
- added new merge function for ports: Duplicated port number will be merged, each port number is splitted by comma.
-  empty string will be return if there is no listening port.
=> display listening ports for each service when uses curveadm status

configs/bs/stand-alone/format.yaml
=> fixes example of format.yaml in standalone cluster

cli/command/cmd.go, cli/command/exec.go, cli/command/playground/enter.go, internal/tools/ssh.go
issue #153
usage:
curveadm exec 0e5d809f16b4 ps
curveadm exec 0e5d809f16b4 curve_ops_tool status
curveadm exec 0e5d809f16b4 -- ps -ef
Signed-off-by: Wangpan <aspirer2004@gmail.com>
```
netease@hih-l-9493:~/curveadm$ ./bin/curveadm exec -h
Usage:  curveadm exec ID [OPTIONS]
Exec a cmd in service container
Options:
-h, --help   Print usage
netease@hih-l-9493:~/curveadm$ ./bin/curveadm exec 0e5d809f16b4 
Connection to 127.0.0.1 closed.
netease@hih-l-9493:~/curveadm$ ./bin/curveadm exec 0e5d809f16b4 -h
Usage:  curveadm exec ID [OPTIONS]
Exec a cmd in service container
Options:
-h, --help   Print usage
netease@hih-l-9493:~/curveadm$ ./bin/curveadm exec 0e5d809f16b4 ps
PID TTY          TIME CMD
1652 pts/3    00:00:00 ps
Connection to 127.0.0.1 closed.
netease@hih-l-9493:~/curveadm$ …
```
=> feature(*): support exec subcommand

cli/command/format.go, internal/playbook/factory.go, internal/task/task/bs/format.go, internal/task/task/bs/format_stop.go
feat: 支持一键停止磁盘格式化，包括：停止容器，删除fstab记录，umount 挂载的磁盘
test：简单测试了：单节点单盘、单节点多盘、多节点多盘
curveadm run result:
step1:  check node docker,fstab, mountpoint not exist
step2: curveadm run format ,and check docker,fstab,mountpoint  exist
step3: curveadm stop format ,check docker, fstab,mountpoint delete
https://github.com/opencurve/curveadm/issues/156
=> feat: support one-click stop format

configs/bs/cluster/scale-out.yaml, configs/bs/cluster/topology.yaml
related to #146 
we should change the `replica` to a more meanful word finally.
Signed-off-by: Wangpan <aspirer2004@gmail.com>
=> add comments for `replicas`

internal/task/task/checker/kernel.go, internal/task/task/checker/kernel_test.go
Fixed: #225
Have passed `make test`.
=> [fix] add support for recognizing kernel versions like "3.15.0_.*"

internal/task/task/checker/network.go
Related to #226 and #214.
Solution: execute the `ss` command in a temporary container to precheck for ports in use instead.
Side effects: the port precheck process will now take a bit longer, since we need to pull image, create a container, start the container, exec the `ss` command for each port, and then stop and remove the container.
=> [fix] older versions of the ss command do not have the --no-header option

internal/configure/topology/dc_get.go, internal/configure/topology/dc_item.go, internal/task/task/common/create_container.go, internal/task/task/playground/script/entrypoint.sh
Issue Number: https://github.com/opencurve/curve/issues/2261
Curve PR: https://github.com/opencurve/curve/pull/2775
=> Add startup parameters for chunkserver

cli/command/deploy.go, cli/command/migrate.go
related: [#308 ](https://github.com/opencurve/curveadm/issues/308)
fix curveadm is performing a type conversion on a nil. 
Solution: Add poolset and diskType to the option choices. So, there won't be a nil.
=> [fix]getClusterPool: performing a type conversion on a nil.

cli/cli/cli.go, cli/command/hosts/list_test.go, cli/command/hosts/playbook.go, internal/configure/hosts/hc_get.go, internal/configure/hosts/hc_item.go, internal/configure/hosts/hosts.go, internal/configure/monitor.go, internal/errno/errno.go, internal/task/task/common/client_status.go, internal/task/task/common/collect_client.go, internal/tui/hosts.go
This PR is about issue #260. I followed the advice of the instructor in the last PR and changed the host (keyword used to express the host identifier) in the configuration file required by curveadm hosts to name, and retained it. hostname keyword
Tests I did:
1. Under the curveadm hosts command, this keyword can work normally, and all commands under hosts can work normally.
2. Under curveadm format, the disk can be formatted normally.
3. The entire process of deploying curvefs can be carried out normally.
The tests I have done may still be incomplete. I hope to get the code review from the instructor and give further suggestions for modifications.
这个pr是有关于issue #260的,我遵循了上一次pr中导师提出的意见,将curveadm hosts 所需的配置文件中的host(用来表达主机标识符的关键字)更改为了name,并保留了hostname关键字
我所做的测试:
1.curveadm …
=> Improve(hosts): use more meaningful name for host name

internal/errno/errno.go, internal/task/step/container.go, internal/task/task/common/client_status.go, internal/tui/client/status.go, pkg/module/docker_cli.go
```bash
Get Client Status: [OK]
Id            Kind     Host         Container Id  Status      Port  Aux Info
--            ----     ----         ------------  ------      ----  --------
2ae7016a1160  curvebs  client-host  8b484fb2ed8a  Up 2 weeks  9002  {"user":"curve","volume":"/test2"}
15ea0603042d  curvebs  server-host  0af4ecea35b7  Up 2 weeks  9001  {"user":"curve","volume":"/test1"}
```
=> [feat] add port for client status
