opencurve/curveadm

- cli/command/reload.go
- internal/tasks/sync_binary.go
- internal/tasks/tasks.go
feature(*): support replace service binary without re-deploy (#2)
> feature(*): support replace service binary without re-deploy (#2)

- README.md
Add documentation for the support command
> README: Add documentation for the support command

- internal/tasks/sync_config.go
fix https://github.com/opencurve/curve/issues/729
sync curvefs_tool config into docker image.
> sync config task: sync curvefs_tool config

- internal/configure/topology_variables.go
add cluster_mds_addr to help add mdsDummyAddr in tools.conf
> variable: add cluster_mds_addr

- internal/task/task/common/create_pool.go
rename build-topology to create-topology
> curveadm: build-topology --> create-topology

- internal/configure/topology/dc_get.go
- internal/task/scripts/createfs.go
- internal/task/step/container.go
- internal/task/task/common/create_pool.go
- internal/task/task/fs/mount.go
fuse-client rm create-fs in init,
so add create-fs in mount
> curveadm: add create fs before umount

- internal/task/step/file.go
- internal/task/task/fs/mount.go
add rename in readfile & installfile
> curveadm: fix syncfile error

- internal/task/task/bs/format_status.go
Close: #70 
add two format status:
1. Mounting
2. Pulling image
> curvebs: add more format status

- internal/task/scripts/wait_chunkservers.go
- internal/task/task/common/create_pool.go
Fixes #58 
Waiting for all chunkservers online before creating logical pool.
> curvebs: fixes create logical pool failed

- cli/cli/cli.go
- cli/command/map.go
- cli/command/status.go
- internal/configure/topology/topology.go
Close #64: if volume name doesn't start with '/', give prompt message to user.
Close #66: fix some prompt message in status command.
> add format check for volume name and fix some prompt message in status command

- cli/curveadm.go
Close #16 
Log all executed commands to audit log file per day.
> improve(*): support audit log

- cli/command/mount.go
- internal/task/scripts/createfs.go
- internal/task/step/container.go
- internal/task/task/common/create_pool.go
- internal/task/task/fs/mount.go
when mount error, but curveadm still show ok.
1. add check status task,When the container status does not change to
exited or dead within 10s, the mount is considered successful.
2. fix create logical pool error when create curvefs
> mount: fix mount status

- cli/command/target/add.go
- internal/task/scripts/map.go
- internal/task/scripts/target.go
- internal/task/task/bs/map.go
> curvebs: report error when map/add_target a non-exist volume

- cli/command/deploy.go
- internal/task/task/bs/balance_leader.go
- internal/task/tasks/items.go
feartue: When executing `deploy` function, balance leader once. close #98 .
> feature: support deploy function to balance leader once

- configs/fs/cluster/topology.yaml
- configs/fs/stand-alone/topology.yaml
- docs/zh/REMEAD.md
> curvefs: remove s3 configs from fs topoloy.yaml

- cli/command/status.go
> Enhancement(*): mark leader mds in status cmd

- cli/command/map.go
Closes: #119
Signed-off-by: Wangpan <hzwangpan@corp.netease.com>
> improve(curvebs): report error when map with root user

- playbook/memcached/hosts.yaml
- playbook/memcached/scripts/clean.sh
- playbook/memcached/scripts/deploy.sh
- playbook/memcached/scripts/status.sh
- playbook/memcached/scripts/stop.sh
1. hosts.yaml template
2. deploy.sh
3. status.sh
4. stop.sh
5. clean.sh
Signed-off-by: Cyber-SiKu <Cyber-SiKu@outlook.com>
> [feat]support memcached by playbook

- internal/task/task/fs/mount.go
1. fix no volumeCluster in tools.conf
Signed-off-by: Cyber-SiKu <Cyber-SiKu@outlook.com>
> [fix]curveadm mount volume

- configs/bs/cluster/client.yaml
- configs/bs/stand-alone/client.yaml
- configs/fs/cluster/client.yaml
- configs/fs/stand-alone/client.yaml
close https://github.com/opencurve/curve/issues/2190
> add `kind` for client.yaml

- .github/workflows/go.yml
add github actions for build and test. The workflow after a push or a pull request to any of the default branch or develop branch
> action: add build and test action
